config/routes.rb
Rails.application.routes.draw do
  resources :events

  devise_for :users

  root 'events#index'
  get 'about' => 'welcome#index', as: :welcome_index
  post 'update_gamertag' => 'welcome#update_gamertag', as: :welcome_update_gamertag
  get 'events_manage' => 'events#events_manage', as: :events_manage
  post 'events/:id/join_event' => 'events#join_event', as: :join_event
  post 'events/:id/approve' => 'events#approve', as: :approve
  get 'events/:id/close' => 'events#close_event', as: :close_event
  get 'events/:id/open' => 'events#open_event', as: :open_event
  get 'events/live_event/chat_window' => 'events#live_event', as: :live_event
  post 'events/:id/announcement_post' => 'events#announcement_post', as: :announcement_post
  

end

app/models/event.rb
class Event < ActiveRecord::Base
	serialize :requests 
	serialize :approvals

end

app/models/event_comment.rb
class EventComment < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  serialize :events_requested       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:index]
  
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token 
  
  
  def index

	if params[:event].present?
		@events = Event.where(system: params[:event][:system], fireteam_group_type: params[:event][:fireteam_group_type], open: true).paginate(page: params[:page], per_page: 10)
	else 
		@events = Event.where(open: true).paginate(page: params[:page], per_page: 10)
	end 
	
    if current_user != nil 
	    user = current_user
	    list = user.events_requested 
	    @my_events = []
	    list.each do |event|    	
	    	@my_events << Event.where(id: event)
	    end 
	end 
  end

  def show
  	event_requests = Event.where(id: params[:id])
  	@leader = User.where(id: event_requests.first.fireteam_leader)
  	@fireteam_array = []
  	if event_requests.first.fireteam_leader == current_user.id 
	  	@request_array = []
	  	@approval_array = []
	  	
	  	event_requests.first.requests.each do |x|
	  		@request_array << User.where(id: x)
	  	end 
	  	
	  	
	  	
	  	event_requests.first.approvals.each do |x|
	  		@approval_array << x
	  	end 
	    	
	end 
	
	event_requests.first.approvals.each do |x|
  		@fireteam_array << User.where(id: x)
  	end 
  	
  	
  	@announcements = EventComment.where(event_id: event_requests.first.id)
  end

  def new

  	if current_user.psn == nil && current_user.xbl == nil 
  		redirect_to edit_user_registration_url, notice: 'You need a PSN/XBL gamertag to post a new event.'
  	else 
    @event = Event.new
    end 
  end

  def edit
  	event = Event.where(id: params[:id])
  	if event.first.fireteam_leader != current_user.id 
  		redirect_to root_url, notice: 'Not manager of this event, unable to edit.'
  	end 
  end

  def create
    @event = Event.new(event_params)
    
    @event.fireteam_leader = current_user.id
	@event.requests = [ ]
	@event.approvals = [ ]
	@event.open = true
	
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  
  def events_manage
  	@events = Event.where(fireteam_leader: current_user.id)
  	
  	if !@events.present?
  		redirect_to root_url, notice: 'You have no events to manage.' 
  	end 
  
  end 
  
  
  def join_event 
  	event = Event.where(id: params[:id])
  	@gamertag = 0
  	
  	if current_user.psn != nil 
  		@gamertag += 1
  	end 
  	
  	if current_user.xbl != nil 
  		@gamertag += 1
  	end 
  	
  	if event != nil 
  		if !current_user.guardian_type?
	   		redirect_to edit_user_registration_url, notice: 'Before you request to join an event please list your PSN/XBL gamertag Guardian Type and Level!!' 
	   	elsif @gamertag < 1
	   		redirect_to edit_user_registration_url, notice: 'You do not have a PSN/XBL gamertag listed!!' 
	   	else 
	   		event.first.requests << current_user.id 
	  		event.first.save
	  		
	  		current_user.events_requested << event.first.id
	  		current_user.save
	  		
	  		redirect_to root_url, notice: 'Your request to join this event has been sent, awaiting approval!!' 
	  	end 
  	end 
  end 
  
  
  def live_event 
  
  end 
  
  
  def announcement_post
  	EventComment.create(event_id: params[:id], user_id: current_user.id, comment: params[:announcement])	
  	redirect_to(:back)
  end 
  
  def approve
  
  	event = Event.where(id: params[:id])
  	user = User.where(id: params[:user_id])
  	
  	event.first.approvals << user.first.id 
  	event.first.save
  	redirect_to(:back)

  end 
  
  def close_event
  	update_event = Event.where(id: params[:id])
  	update_event.first.open = false 
  	update_event.first.save
  	redirect_to(:back)
  end 
  
  def open_event
  	update_event = Event.where(id: params[:id])
  	update_event.first.open = true 
  	update_event.first.save
  	redirect_to(:back)
  end 
    
  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:fireteam_leader, :fireteam_group_type, :level, :comments, :video_url, :date_time, :system)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
skip_before_filter :verify_authenticity_token  

def index

end 

def update_gamertag
	user = current_user 
	
	if params[:psn].present?
		user.update_attributes(psn: params[:psn])
	end 
	
	
	if params[:xbl].present?
		user.update_attributes(xbl: params[:xbl])
	end 
	
	
	if params[:destiny].present?
		user.update_attributes(destiny: params[:destiny])
	end 
	
	if params[:event][:fireteam_group_type].present?
		user.update_attributes(guardian_type: params[:event][:fireteam_group_type])
	end
	
	if params[:level].present?
		user.update_attributes(guardian_level: params[:level])
	end 		 
	redirect_to root_url
end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fireteam_leader %><br>
    <%= current_user.email   %><br>
    <% if current_user.psn.present?%>PSN: <%= current_user.psn %><% else %>PSN: NONE<% end %><br>
    <% if current_user.xbl.present?%>XBL: <%= current_user.xbl %><% else %>XBL: NONE<% end %><br>
    <% if current_user.destiny.present?%>Destiny: <%= current_user.destiny %><% else %> Destiny: It would be helpful to list your Destiny profile.<% end %><br>
  </div>
  <div class="field">
  	<label for="profile_name">Event Type</label>
	<select class="form-control" name="event[fireteam_group_type]">
		<option value="Raid - Vault of Glass">Raid - Vault of Glass</option>
		<option value="Strike Team - Weekly">Strike Team - Weekly</option>
		<option value="Strike Weekly Nightfall">Strike Weekly Nightfall</option>
		<option value="Daily Heroic Story">Daily Heroic Story</option>
		<option value="Strike Team - Devil's Lair">Strike Team - Devil's Lair</option>
		<option value="Strike Team - The Summoning Pits">Strike Team - The Summoning Pits</option>
		<option value="Strike Team - The Nexus">Strike Team - The Nexus</option>
		<option value="Strike Team - Winter's Run">Strike Team - Winter's Run</option>
		<option value="Strike Team - Cerberus Vae III">Strike Team - Cerberus Vae III</option>
		<option value="Strike Team - Dust Palace">Strike Team - Dust Palace</option>
		<option value="PvP - Control">PvP - Control</option>
		<option value="PvP - Clash">PvP - Clash</option>
		<option value="PvP - Rumble">PvP - Rumble</option>
		<option value="PvP - Skirmish">PvP - Skirmish</option>
		<option value="PvP - Salvage">PvP - Salvage</option>
		<option value="PvP - Iron Banner">PvP - Iron Banner</option>
	</select>
  </div>
  <div class="field">
    <%= f.label :recommended_level %><br>
    <%= f.number_field :level, class: 'form-control'   %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments, class: 'form-control'   %>
  </div>
<!--
  <div class="field">
    <%= f.label :video_sample_url %><br>
    <%= f.text_field :video_url, class: 'form-control'   %>
  </div>
-->
  <div class="field">
    <%= f.label :date_time %><br>
    <strong>Time is submitted in UTC, use the UTC to local time converter to submit the correct time.</strong>
    <font color="red">Example: 22:00 UTC converts to 17:00 CDT (5:00 pm)</font><br>
    
    <%= f.datetime_select :date_time, class: 'form-control'   %>
  </div>
  
  <div class="field">
  <script type="text/javascript" id="WolframAlphaScriptb96801c254a54a8ec4feb22a54f14b1d" src="http://www.wolframalpha.com/widget/widget.jsp?id=b96801c254a54a8ec4feb22a54f14b1d"></script>
  </div>
<br>

<style>

table#wolframAlphaWidget76104, div#wolframAlphaWidget76104 {	width: 90%;
}

</style>

<label for="profile_name">System</label>  
<div class="field">
    
<select class="form-control" name="event[system]">
  <option value="PS4">PS4</option>
  <option value="Xbox One">Xbox One</option>
  <option value="PS3">PS3</option>
  <option value="Xbox 360">Xbox 360</option>
</select>

<br>    
    
    
    
    
    
    
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'View', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/events_manage.html.erb
<% @events.each do |event| %>
	<%= event.fireteam_group_type %>
	<%= link_to 'Show', event %>
	<% if current_user != nil %>
		<% if event.fireteam_leader == current_user.id %>
			<%= link_to 'Edit', edit_event_path(event) %>
			<%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>	
	<% end %><br>
<% end %> 

app/views/events/index.html.erb
<div class="row">
  <div class="col-xs-6 col-sm-6 col-md-6">
	<form action="/events/new" method="get">
	<button class="btn btn-success">Post New Event </button>
	</form>
  </div>
  <% if current_user != nil%>
  <div class="col-xs-6 col-sm-6 col-md-6">
	<form action="/events_manage" method="get">
		<button class="btn btn-danger">Manage My Events </button>
	</form>	  
  </div>
  <% end %>
</div>


<br>





<!-- Nav tabs -->
<ul class="nav nav-tabs" role="tablist">
  <li class="active"><a href="#home" role="tab" data-toggle="tab">Events</a></li>
  <li><a href="#profile" role="tab" data-toggle="tab">My Events</a></li>
  <li><a href="events/live_event/chat_window" onclick="window.open(this.href); return false;" onkeypress="window.open(this.href); return false;"" role="tab" data-toggle="tab">Live Event Building</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="home">
<br>

<form role="form" action="/events" method="get">
  <div class="field">
  	<label for="profile_name">System</label>
	<select class="form-control" name="event[system]">
		<option value="PS4">PS4</option>
		<option value="PS3">PS3</option>
		<option value="Xbox One">Xbox One</option>
		<option value="Xbox 360">Xbox 360</option>
	</select>
  </div>
  <div class="field">
  	<label for="profile_name">Event Type</label>
	<select class="form-control" name="event[fireteam_group_type]">
		<option value="Raid - Vault of Glass">Raid - Vault of Glass</option>
		<option value="Strike Team - Weekly">Strike Team - Weekly</option>
		<option value="Strike Weekly Nightfall">Strike Weekly Nightfall</option>
		<option value="Daily Heroic Story">Daily Heroic Story</option>
		<option value="Strike Team - Devil's Lair">Strike Team - Devil's Lair</option>
		<option value="Strike Team - The Summoning Pits">Strike Team - The Summoning Pits</option>
		<option value="Strike Team - The Nexus">Strike Team - The Nexus</option>
		<option value="Strike Team - Winter's Run">Strike Team - Winter's Run</option>
		<option value="Strike Team - Cerberus Vae III">Strike Team - Cerberus Vae III</option>
		<option value="Strike Team - Dust Palace">Strike Team - Dust Palace</option>
		<option value="PvP - Control">PvP - Control</option>
		<option value="PvP - Clash">PvP - Clash</option>
		<option value="PvP - Rumble">PvP - Rumble</option>
		<option value="PvP - Skirmish">PvP - Skirmish</option>
		<option value="PvP - Salvage">PvP - Salvage</option>
		<option value="PvP - Iron Banner">PvP - Iron Banner</option>
	</select>
  </div>
  <button type="submit" class="btn btn-default">Submit</button>  <a href='/'>Reset</a>
</form>
<br>

<% @events.each do |event| %>
<div class="row" style="border-bottom:1px solid black; border-top:1px solid black;">  
<div class="col-md-6 col-xs-6">
<ul class="list-group">
	<strong><% if event.system == 'PS4' || event.system == 'PS3' %><font color="blue"><%= event.system %></font><%else%><font color="green"><%= event.system %></font><% end %>: <%= event.fireteam_group_type %></strong><br><font color="red">Recommended Level: <%=event.level %></font><br>
	<% person = User.where(id: event.fireteam_leader).first %>
	Sherpa: <%= person.email %> <font color="blue">PSN:<%= person.psn %></font> <font color="green">XBL: <%= person.xbl %></font>
	<br>
	Guardian Count: <%= event.approvals.count + 1  %>
	<br>
	<%= link_to 'View', event %>
	<% if current_user != nil %>
		<% if event.fireteam_leader == current_user.id %>
			<%= link_to 'Edit', edit_event_path(event) %>
			<%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>	
	<% end %>
</div>	
</ul>
<div class="col-md-6 col-xs-6">
<ul class="list-group">
<strong><font color="red">Date/Time: <%= local_time(event.date_time)  %></font></strong>
<p><%= event.comments.truncate(75) %></p>	
</ul>
</div>

</div>



<% end %> 

 <%= will_paginate @events %> 
	  
	  
	  
  </div>
  <div class="tab-pane" id="profile">
  <br>
<% if current_user != nil %>	  
<% @my_events.each do |list| %>
<div class="row">  
<div class="col-md-6 col-xs-6">
<% if !list.empty? %>
<ul class="list-group">
	<strong><% if list.first.system == 'PS4' || list.first.system == 'PS3' %><font color="blue"><%= list.first.system %></font><%else%><font color="green"><%= list.first.system %></font><% end %>: <%= list.first.fireteam_group_type %></strong><br><font color="red">Recommended Level: <%=list.first.level %></font><br>
	<% leader = User.where(id: list.first.fireteam_leader).first %>
	Sherpa: <%= leader.email %> <font color="blue">PSN:<%= leader.psn %></font> <font color="green">XBL: <%= leader.xbl %></font>
	<br>
	Guardian Count: <%= list.first.approvals.count + 1  %>
	<br>
	<%= link_to 'View', list.first %>
	<% if current_user != nil %>
		<% if list.first.fireteam_leader == current_user.id %>
			<%= link_to 'Edit', edit_event_path(list) %>
			<%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>	
	<% end %>
</div>	
</ul>

<div class="col-md-6 col-xs-6">
<ul class="list-group">
<p>Date/Time: <%= local_time(list.first.date_time)  %></p>
<p><%= list.first.comments.truncate(75) %></p>	
<p><% if list.first.approvals.include?(current_user.id) %> <font color="gold"> <h5>APPROVED</h5> </font><% else %><font color="gold"> Awaiting approval... </font><% end %></p>
</ul>
<% end %>
</div>

</div>


<% end %>
<% end %>	  
	  
</div>
  <div class="tab-pane" id="messages">
  	 <br> 
  	  <p> Keep is simple, user your PSN/XBL gamertag as the username. If you have any problems chatting click on the profile icon and sign out.</p>
  	 <br>
	  <div id="tlkio" data-channel="destinysherpa" style="width:100%;height:400px;"></div><script async src="http://tlk.io/embed.js" type="text/javascript"></script>
  </div>
  
  
</div>



<script>

	$('#myTab a').click(function (e) {
	  e.preventDefault()
	  $(this).tab('show')
	})

</script>

app/views/events/live_event.html.erb
<div id="tlkio" data-channel="destinysherpa" style="width:100%;height:400px;"></div><script async src="http://tlk.io/embed.js" type="text/javascript"></script>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<div class="row">
  <% if @event.fireteam_leader == current_user.id %>
	  <% if @event.open == true || @event.open == nil%>
	  <center><p> closing the event when you have completed your Fireteam, it will no longer be listed for others to request to join.</p></center>
	  <div class="col-xs-6 col-sm-6 col-md-6">
		<form action="/events/<%= @event.id %>/close" method="get">
		<button class="btn btn-danger">Close Event </button>
		</form>
	  </div>
	  <%else%> 
	  <p>You have closed this event...</p>
	  <div class="col-xs-6 col-sm-6 col-md-6">
		<form action="/events/<%= @event.id %>/open" method="get">
		<button class="btn btn-defaul">Open Event </button>
		</form>
	  </div>  
	  <% end %>
  <%end%>

</div>
<br>

<p>
  <strong>Fireteam leader:</strong>
  <p><%= @leader.first.email %></p><font color="blue">PSN:<%= @leader.first.psn %></font> <font color="green"><br>XBL: <%= @leader.first.xbl %></font>
  <br><% if @leader.first.destiny != nil%><a href="<%= @leader.first.destiny%>">View Destiny Profile</a><%else%><p>No Destiny Profile</p><%end%>
</p>

<p>
  <strong>Fireteam group type:</strong>
  <%= @event.fireteam_group_type %>
</p>

<p>
  <strong>Recommended Level:</strong>
  <%= @event.level %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @event.comments %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @event.video_url %>
</p>

<p>
  <strong>Date time:</strong>
  <font color="red"><%= @event.date_time.localtime %></font>
</p>

<p>
  <strong>System:</strong>
  <%= @event.system %>
</p>

<% if @event.fireteam_leader == current_user.id %> 
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>



<h4>Requests to join event:</h4>
<div class="row">
<% @request_array.each do |f|%>
	
	<% if !@approval_array.include?(f.first.id) %>
	<div class="col-xs-6 col-sm-6 col-md-3">
	<ul class="list-group">
		<li class="list-group-item"><%= f.first.email %></li>
		<li class="list-group-item"><font color="blue">PSN:<%= f.first.psn %></font> <font color="green">XBL: <%= f.first.xbl %></font></li>
		<li class="list-group-item">Guardian: <%= f.first.guardian_type %></li>
		<li class="list-group-item">Level: <%= f.first.guardian_level %></li>
		<li class="list-group-item">
			<form action="/events/<%= @event.id %>/approve" method="post">
				<input type="hidden" name="user_id" value="<%= f.first.id %>">
				<button class="btn btn-danger">Approve</button>
			</form>	 				
		</li>
		<%if f.first.destiny != nil %><li class="list-group-item"><a href="<%= f.first.destiny%>">View Destiny Profile</a></li>
		<% else %> <li class="list-group-item"><p>No Destiny Profile</p></li>
		<% end %>	
	</ul>
	</div>
	<% end %>
	
<% end %>

</div>


<% else %>

	<% if !@event.requests.include?(current_user.id)%>
	<form action="/events/<%= @event.id %>/join_event" method="post">
		<button class="btn btn-danger">Join Event </button>
	</form>	  
	<% end %>
<% end %>


<h4>Fireteam:</h4>
<div class="row">
	<% @leader.each do |f|%>
		<div class="col-xs-6 col-sm-6 col-md-3">
		<ul class="list-group">
			<li class="list-group-item"><%= f.email %></li>
			<li class="list-group-item"><font color="blue">PSN:<%= f.psn %></font> <font color="green">XBL: <%= f.xbl %></font></li>
			<li class="list-group-item">Guardian: <%= f.guardian_type %></li>
			<li class="list-group-item">Level: <%= f.guardian_level %></li>
			<%if f.destiny != nil %><li class="list-group-item"><a href="<%= f.destiny%>">View Destiny Profile</a></li>
			<% else %> <li class="list-group-item"><p>No Destiny Profile</p></li>
			<% end %>
		</ul>
		</div>
	<% end %>
	
	<% if @fireteam_array != nil %>
	<% @fireteam_array.each do |f|%>
		<div class="col-xs-6 col-sm-6 col-md-3">
		<ul class="list-group">
			<li class="list-group-item"><%= f.first.email %></li>
			<li class="list-group-item"><font color="blue">PSN:<%= f.first.psn %></font> <font color="green">XBL: <%= f.first.xbl %></font></li>
			<li class="list-group-item">Guardian: <%= f.first.guardian_type %></li>
			<li class="list-group-item">Level: <%= f.first.guardian_level %></li>
			<%if f.first.destiny != nil %><li class="list-group-item"><a href="<%= f.first.destiny%>">View Destiny Profile</a></li>
			<% else %> <li class="list-group-item"><p>No Destiny Profile</p></li>
			<% end %>			
		</ul>
		</div>
	<% end %>
	<% end %>

</div>


<h4>Announcements:</h4>
<p> You need to be part of this fireteam to view or post announcements.</p>
<% fireteam = [] %>
<% @fireteam_array.each do |f| %>
	<% fireteam << f.first.id%>
<% end %>
<% if fireteam.include?(current_user.id) || @event.fireteam_leader == current_user.id%>
	<form role="form" action="/events/<%= @event.id %>/announcement_post" method="post">
	  <div class="form-group form-group-lg">
	    <div class="col-sm-10">
	      <input class="form-control" type="text" id="formGroupInputLarge" name="announcement" placeholder="post an announcement">
	    </div>
	  </div>
	  <button type="submit" class="btn btn-default">Submit</button>
	</form>
	
	<br>
	<br>
	<%@announcements.each do |anounce|%>
	<ul class="list-group">
		<li class="list-group-item"><% person = User.where(id: anounce.user_id)%><strong><%=person.first.email%>:</strong> <%= anounce.comment %> <p><%= anounce.created_at.localtime  %></p></li>
	</ul>
	<% end %>
<% end %>

<br>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Destiny Sherpa</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<% if user_signed_in? %>
      	
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
      	<li></li>
      	<li><%= link_to "About", welcome_index_path, method: :get, :class => 'navbar-link'  %></li>
      	<li><%= link_to "#{current_user.email}", edit_user_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
      </ul>
      <% else %>      
      	
      </ul>
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "About", welcome_index_path, method: :get, :class => 'navbar-link'  %></li>
      	<li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
      </ul>	  	
      
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Destiny Sherpa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	
	<!-- Optional theme -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	
	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  
  
  
</head>
<body>
<%= render 'layouts/navigation' %>
<% if notice %>   <p class="alert alert-success"><%= notice %></p> <% end %> <% if alert %>   <p class="alert alert-danger"><%= alert %></p> <% end %>

<div class="container bs-docs-container">
<%= yield %>
</div>
</body>
</html>